---
verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[yum-kernel-osuosl::default]
      - recipe[yum-kernel-osuosl::install]
  - name: install
    run_list:
      - recipe[yum-kernel-osuosl::install]
