name             'yum-kernel-osuosl'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apachev2'
issues_url       'https://github.com/osuosl-cookbooks/yum-kernel-osuosl/issues'
source_url       'https://github.com/osuosl-cookbooks/yum-kernel-osuosl'
description      'Installs/Configures yum-kernel-osuosl'
long_description 'Installs/Configures yum-kernel-osuosl'
version          '0.1.0'

supports         'centos', '~> 7.0'
